const CacheKeys = {
	DISABLED_USER: 'DISABLED_USER',
	ALL_USER_LIST: 'ALL_USER_LIST',
	ALL_USER_LIST_IN_VIEWER_GROUP: 'ALL_USER_LIST_IN_VIEWER_GROUP',
	ALL_USER_LIST_IN_ADMIN_GROUP: 'ALL_USER_LIST_IN_ADMIN_GROUP',
	ALL_USER_LIST_IN_EDITOR_GROUP: 'ALL_USER_LIST_IN_EDITOR_GROUP',
};

module.exports = CacheKeys;
