const taskTypes = {
	SYNC_DEVICE: 'SYNC_DEVICE',
	SYNC_DEVICE_BEARING_DISTANCE: 'SYNC_DEVICE_BEARING_DISTANCE',
	SEND_MAIL: 'SEND_MAIL',
	SEND_DEV_MAIL: 'SEND_DEV_MAIL',
	UPDATE_LATEST_EVENT: 'UPDATE_LATEST_EVENT',
	SYNC_DEVICE_HEALTH: 'SYNC_DEVICE_HEALTH',
	SYNC_INACTIVE_DEVICE_HEALTH: 'SYNC_INACTIVE_DEVICE_HEALTH',
	REFRESH_DEVICE_VIEW: 'REFRESH_DEVICE_VIEW',
	REFRESH_DEVICE_VIEW_ALL: 'REFRESH_DEVICE_VIEW_ALL',
	REFRESH_DEVICE_VIEW_MONTHLY: 'REFRESH_DEVICE_VIEW_MONTHLY',
	SYNC_STAGING_DB: 'SYNC_STAGING_DB',
	REFRESH_DEVICE_SUCCESS_RATE: 'REFRESH_DEVICE_SUCCESS_RATE',
	SEND_ALERT_MAIL: 'SEND_ALERT_MAIL',
	PROCESS_ALERT: 'PROCESS_ALERT',
	CHECK_EVENT_FOR_ALERT: 'CHECK_EVENT_FOR_ALERT',
	CHECK_EVENT_FOR_WEBHOOK: 'CHECK_EVENT_FOR_WEBHOOK',
	PROCESS_EVENT_WEBHOOK: 'PROCESS_EVENT_WEBHOOK',
	DB_BACKUP: 'DB_BACKUP',
	UPLOAD_EVENT_PAYLOAD_2S3: 'UPLOAD_EVENT_PAYLOAD_2S3',
	UPLOAD_DEVICE_PAYLOAD_2S3: 'UPLOAD_DEVICE_PAYLOAD_2S3',
};

module.exports = taskTypes;
